### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by kentaurse** [mafik/automat#1]
I'm a computer science PhD & a former Google employee from Poland. My passion is creating polished & fun software that empowers people. Your sponsorship would allow me to hire help & grow the open-source community by mentoring new CS students.

What you said is truly wonderful.
I want to be friends with you.

**Comment by mafik** [comment]
Absolutely! If you want to get in touch, you can drop by my live stream either at YouTube or at Twitch:
https://www.youtube.com/@MarekRogalski
https://twitch.tv/maf_pl
