### ISSUE TITLE
https://automat.org/ : clicking video player causes video restart

### ISSUE THREAD

**Issue by 12v** [mafik/automat#2]
Hey, this is great!

Noticed a couple of things on the website which may not be intended:
1. hovering over the video player shows browser video controls
2. clicking the video player shows browser video controls
3. clicking the video player restarts the video

macOS 13.1
Brave 1.70.117

https://github.com/user-attachments/assets/ebd725b4-dde0-48ac-b79c-14c3c8b34ef5

**Comment by mafik** [comment]
Thanks!
