### ISSUE TITLE
automat.org: align cassette angle with video player and enhance napkin interaction

### ISSUE THREAD

**Issue by zackha** [mafik/automat#4]
Hey @mafik,

I noticed a small but potentially impactful detail on the Automat website. When a cassette is dragged and dropped, its angle changes randomly, which might not align perfectly with the angle of the video player it’s placed into. While this might not be a critical bug, ensuring that the angle of the cassette matches the video player’s angle could enhance the overall smoothness and polish of the user experience.

Additionally, for the napkin interaction, it might be a nice touch to allow users to interact with it more dynamically—for instance, letting users dispose of it by dropping it into the coffee, where it could dissolve or disappear.

These adjustments could add to the website's interactive charm and improve the overall cohesiveness of the experience.

Best regards,

https://github.com/user-attachments/assets/c454f9ce-dc6e-4969-8fec-501e401681b2

**Comment by mafik** [comment]
Good catch. The video player issue is now fixed in [1ff1401](https://github.com/mafik/automat/commit/1ff1401dd06ade81236e719a80ba8c9f6e5ad69f).

Regarding napkin - yeah. I've had trouble coming up with a way to animate the napkin but I'm thinking we could do a tiny cloth simulation.

**Comment by zackha** [comment]
Thanks @mafik,

You have resolved the issue with a very minor adjustment in the code—congratulations! For now, the napkin can stay as it is. Once Automat reaches its beta version and people start flocking to star the repository, everyone will likely compete to open issues anyway.
